### ISSUE TITLE
上传到 Amazon S3 发生错误，请检查配置是否正确，Error: write EPROTO 953273432:error:10000410:SSL 

### ISSUE THREAD

**Issue by gdutxiaoxu** [wayjam/picgo-plugin-s3#13]
2022-04-26 17:33:38 [PicGo ERROR] 上传到 Amazon S3 发生错误，请检查配置是否正确 
2022-04-26 17:33:38 [PicGo ERROR] 
------Error Stack Begin------
Error: write EPROTO 953273432:error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE:../../third_party/boringssl/src/ssl/tls_record.cc:587:SSL alert number 40
953273432:error:1000009a:SSL routines:OPENSSL_internal:HANDSHAKE_FAILURE_ON_CLIENT_HELLO:../../third_party/boringssl/src/ssl/handshake.cc:580:

    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:83:16)
-------Error Stack End------- 
2022-04-26 17:33:38 [PicGo WARN] failed 
2022-04-26 17:33:38 [PicGo ERROR] 
------Error Stack Begin------
Error: write EPROTO 953273432:error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE:../../third_party/boringssl/src/ssl/tls_record.cc:587:SSL alert number 40
953273432:error:1000009a:SSL routines:OPENSSL_internal:HANDSHAKE_FAILURE_ON_CLIENT_HELLO:../../third_party/boringssl/src/ssl/handshake.cc:580:

    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:83:16)
-------Error Stack End------- 
2022-04-26 17:33:38 [PicGo ERROR] 
------Error Stack Begin------
Error: write EPROTO 953273432:error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE:../../third_party/boringssl/src/ssl/tls_record.cc:587:SSL alert number 40
953273432:error:1000009a:SSL routines:OPENSSL_internal:HANDSHAKE_FAILURE_ON_CLIENT_HELLO:../../third_party/boringssl/src/ssl/handshake.cc:580:

    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:83:16)
-------Error Stack End-------

**Comment by xinglong-zh** [comment]
提问时间比较远，不知道你还是否需要。

---------------
这种一般都是配置问题，以我用的cloudflare 为例：
还需要配置**自定义节点**，**自定义域名**。这两者配置完成之后，就可以正常使用了。
