### ISSUE TITLE
自定义域名后面的路径能不能自定义裁剪一下

### ISSUE THREAD

**Issue by zhiyue** [wayjam/picgo-plugin-s3#45]
比如填入的路径是：`images/uploads/{year}{month}/original/{md5}.{extName}`
希望能得到的是： `image.domain.com/{year}{month}/original/{md5}.{extName}`

**Comment by wayjam** [comment]
这个需求的原因是否是，这些图片对外提供访问的时候会有一定的 rewrite？所以希望这里上传后返回的路径跟上传的路径不一致。

如果是的会我觉得可以做一个 `outputUrlRewriteRegexp` 的配置，配置入正则Pattern，输出的时候用这个正则处理一下路径可能更灵活一些

**Comment by fscarmen** [comment]
是的，我也有这个需求，因为我把账户PAT和路径都经过 worker rewrite 了。

比如填入的路径是：images/{fileName}.{extName}
希望能得到的是： image.domain.com/{fileName}.{extName}

**Comment by wayjam** [comment]
Released v1.4.0-beta.1 [Latest](https://github.com/wayjam/picgo-plugin-s3/releases/latest)

重写了输出路径的格式化方法。请查看 [`README.md`](https://github.com/wayjam/picgo-plugin-s3) 的 `outputURLPattern`

**Comment by fscarmen** [comment]
<img width="863" alt="image" src="https://github.com/user-attachments/assets/3e3315ea-fa0f-40c8-b9b4-ee14f0585d49">

我多次升级，之后重启picgo，看版本仍然是 1.3.9 呢，应该如何处理？

**Comment by wayjam** [comment]
@fscarmen 新版引入了 `mime` 的 esm 版，GUI版PIcGO加载不出来了，在 `1.4.0-beta.2` 修复了。

CLI版升级方式：

```
picgo add picgo-plugin-s3@1.4.0-beta.2
```

GUI版升级方式：

界面 npm api 可能有 cache，没有搜出来 1.4.0 版则可以先进去以下目录，然后使用 `npm install picgo-plugin-s3@1.4.0-beta.2`

> Windows: %APPDATA%\picgo\data.json
> Linux: $XDG_CONFIG_HOME/picgo/data.json or ~/.config/picgo/data.json
> macOS: ~/Library/Application\ Support/picgo/data.json

**Comment by fscarmen** [comment]
谢谢啊，可以了。我以为自己pc的问题，搞了一整天都不行。

**Comment by fscarmen** [comment]
> Released v1.4.0-beta.1 [Latest](https://github.com/wayjam/picgo-plugin-s3/releases/latest)
> 
> 重写了输出路径的格式化方法。请查看 [`README.md`](https://github.com/wayjam/picgo-plugin-s3) 的 `outputURLPattern`，支持了更多的 payload 和正则替换，更加灵活，理论上可以适应所有场景。

这个  outputURLPattern 太好用了，我是 `https://<worker 自定义域名>/{fullName}`

**Comment by fscarmen** [comment]
> @fscarmen 新版引入了 `mime` 的 esm 版，GUI版PIcGO加载不出来了，在 `1.4.0-beta.2` 修复了。
> 
> CLI版升级方式：
> 
> ```
> picgo add picgo-plugin-s3@1.4.0-beta.2
> ```
> 
> GUI版升级方式：
> 
> 界面 npm api 可能有 cache，没有搜出来 1.4.0 版则可以先进去以下目录，然后使用 `npm install picgo-plugin-s3@1.4.0-beta.2`
> 
> > Windows: %APPDATA%\picgo\data.json
> > Linux: $XDG_CONFIG_HOME/picgo/data.json or ~/.config/picgo/data.json
> > macOS: ~/Library/Application\ Support/picgo/data.json

1.4.0-beta.2 在上传文件到 Backblaze B2 桶时不成功，日志是 

```
------Error Stack Begin------
Error: Failed to upload to S3: Unsupported value for canned acl 'public-read'
    at Object.createUploadTask (/Users/fscarmen/Library/Application Support/picgo/node_modules/picgo-plugin-s3/dist/uploader.js:70:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async Object.upload [as handle] (/Users/fscarmen/Library/Application Support/picgo/node_modules/picgo-plugin-s3/dist/index.js:26:19)
    at async je.doUpload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:19834)
    at async je.start (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:18605)
    at async $t.upload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:74899)
    at async Object.upload (/Applications/PicGo.app/Contents/Resources/app.asar/index.js:2:687302)
    at async mr (/Applications/PicGo.app/Contents/Resources/app.asar/index.js:2:690051)
-------Error Stack End------- 
```

之前使用1.3.9 上传这个B2 桶时，要把 ACL 那填留空。现在1.4.0-beta.2 我也是留空的，在配置信息里也是 `"acl": "",`，但看报错好像仍然是使用了acl: public-read ，请查查。

另外endpoint 一定要加上协议头https://，如果不加也能提交配置但上传会失败。而像b2桶这里没有提示https:// ，如果简单容易处理的，希望可以加个提交限制，提示需要有协议。如果复杂的，在这里指示用户一下也好

<img width="597" alt="image" src="https://github.com/user-attachments/assets/c2b65365-1467-46ae-bd9e-c098f6d8113c">


<img width="1093" alt="image" src="https://github.com/user-attachments/assets/450c590e-e13e-4ab0-aeac-13b3ceff8e8e">

**Comment by wayjam** [comment]
@fscarmen R2的ACL设置成 `private` 试试

**Comment by fscarmen** [comment]
> @fscarmen R2的ACL设置成 `private` 试试

这个我之前试过了，忘记说而已。也是不行的。这个问题是在1.4.0才有的。

```
2024-12-11 19:51:10 [PicGo ERROR] 
------Error Stack Begin------
Error: Failed to upload to S3: UnknownError
    at Object.createUploadTask (/Users/fscarmen/Library/Application Support/picgo/node_modules/picgo-plugin-s3/dist/uploader.js:70:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async Object.upload [as handle] (/Users/fscarmen/Library/Application Support/picgo/node_modules/picgo-plugin-s3/dist/index.js:26:19)
    at async je.doUpload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:19834)
    at async je.start (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:18605)
    at async $t.upload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:74899)
    at async Object.upload (/Applications/PicGo.app/Contents/Resources/app.asar/index.js:2:687302)
    at async mr (/Applications/PicGo.app/Contents/Resources/app.asar/index.js:2:690051)
-------Error Stack End------- 

```

**Comment by fscarmen** [comment]
大佬，一係你留email俾我，我直接俾个b2桶你试，咁样快D

**Comment by wayjam** [comment]
> 大佬，唔係 R2啊（这个没有问题），係 Backblaze B2 桶。一係你留email俾我，我直接俾个b2桶你试，咁样快D

奇怪 B2 我也是用了 private 上传成功了。我在 `v1.4.0-beta.3` 将 ACL 默认值恢复成空，你试下如果还不行，你可以在我 blog 的 about 页找到 email。

**Comment by fscarmen** [comment]
可以了，大佬。我定点到问题了，我上传的测试图片文件名有空格，导致不成功，这个是上几天别人使用我项目同步时，说有空格的文件会出问题，我弄了一个测试的，忘记这点了。真是对唔住大佬。

另外上传成功后那个 {fullName} 在 B2桶是生效了，但这个占位符在 outputURLPattern 里好像不能用 

提示这个

<img width="390" alt="image" src="https://github.com/user-attachments/assets/429408f6-8e6f-4f8c-ba2a-14fcf913759d" />
<img width="906" alt="image" src="https://github.com/user-attachments/assets/3191d815-db54-4bbe-bf1f-78476c5d03be" />

**Comment by rakkasumi** [comment]
可以注明一下正则替换表达式中间不能有空格，习惯性的在逗号后面打了空格，检查了半天才发现问题
