### ISSUE TITLE
certificate has expired

### ISSUE THREAD

**Issue by bkfeng** [wayjam/picgo-plugin-s3#8]
之前上传成功过一次，现在上传提示证书过期。
配置应该是没问题的，我在rclone用这个ID和密钥能连接成功

picog版本：2.3.0
插件版本：1.1.3

```
2021-12-03 16:38:00 [PicGo INFO] Before transform 
2021-12-03 16:38:00 [PicGo INFO] Transforming... Current transformer is [path] 
2021-12-03 16:38:00 [PicGo INFO] Before upload 
2021-12-03 16:38:00 [PicGo INFO] beforeUploadPlugins: renameFn running 
2021-12-03 16:38:00 [PicGo INFO] Uploading... Current uploader is [aws-s3] 
2021-12-03 16:38:03 [PicGo ERROR] 上传到 Amazon S3 发生错误，请检查配置是否正确 
2021-12-03 16:38:03 [PicGo ERROR] 
------Error Stack Begin------
Error: certificate has expired
    at TLSSocket.onConnectSecure (_tls_wrap.js:1317:34)
    at TLSSocket.emit (events.js:200:13)
    at TLSSocket.EventEmitter.emit (domain.js:471:20)
    at TLSSocket._finishInit (_tls_wrap.js:792:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:606:12)
-------Error Stack End------- 
```

**Comment by KaidLi** [comment]
同样遇到了这个问题。
* picgo版本 `2.3.0-beta.7`
* 插件版本 `1.1.1`
````
2021-12-07 13:55:08 [PicGo INFO] Before transform 
2021-12-07 13:55:08 [PicGo INFO] Transforming... Current transformer is [path] 
2021-12-07 13:55:08 [PicGo INFO] Before upload 
2021-12-07 13:55:08 [PicGo INFO] beforeUploadPlugins: renameFn running 
2021-12-07 13:55:08 [PicGo INFO] Uploading... Current uploader is [aws-s3] 
2021-12-07 13:55:11 [PicGo ERROR] 上传到 Amazon S3 发生错误，请检查配置是否正确 
2021-12-07 13:55:11 [PicGo ERROR] 
------Error Stack Begin------
Error: certificate has expired
    at TLSSocket.onConnectSecure (_tls_wrap.js:1317:34)
    at TLSSocket.emit (events.js:200:13)
    at TLSSocket.EventEmitter.emit (domain.js:471:20)
    at TLSSocket._finishInit (_tls_wrap.js:792:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:606:12)
-------Error Stack End------- 
````

使用相同配置的shareX上传正常

**Comment by includef** [comment]
我尝试抓包看证书是否真正过期，由于是默认`TLS1.3`加密，但是`js`不是太会，一直没成功看到证书，不过可能确实过期了，因为前几天我打开`www.jianshu.com`也提示证书过期了，看了一眼是刚过期，之前以为大站不会出现这种情况。而且backblaze b2用的是Let's Encrypt的证书，有效期只有三个月，可能经常会出现过期情况。
所以我增加了一个禁用掉证书验证的功能。已`pull request`

**Comment by wayjam** [comment]
@includef @KaidLi 请问你们都是用B2吗？我这边用B2没有出现这个问题

**Comment by includef** [comment]
我的是B2，可能和不同地区对应的节点机房位置有关，证书没及时更新。前两天简书的证书出了问题，某些地区/网络访问网站拿到的就是过期的证书。

**Comment by KaidLi** [comment]
> @includef @KaidLi 请问你们都是用B2吗？

我使用的也是b2

**Comment by icrazt** [comment]
我遇到的同样的问题，也是在使用 B2

**Comment by pscgyLancer** [comment]
我遇到了同样的问题，也是在使用 B2

**Comment by wayjam** [comment]
Released `v1.1.4` 增加 `rejectUnauthorized` 设置
